name: test_image_picker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  permission_handler: 5.1.0+2
  image_picker: ^0.6.7+22
#  dio: ^3.0.10
#  cached_network_image: ^2.0.0
#  intl: ^0.16.1
#  flutter_bloc: 6.1.1
#  equatable: ^1.2.0
#  intl_translation: ^0.17.9
#  fluro: 1.7.8
#  retrofit_generator: ^1.0.2
#  package_info: ^0.4.3+2
#
#  progress_dialog: ^1.2.0
#  platform_device_id: 0.1.3
#  youtube_player_flutter: ^7.0.0+7
#
#  #  timer_builder: ^1.3.0
#  #  multi_image_picker:
#  #  percent_indicator:
#  #    git:
#  #      url: git://github.com/AnhDV580/flutter_percent_indicator.git
#  #      ref: custom_linear_percent_indicator
#  #  flutter_calendar_carousel: ^1.4.12
#  #camera: ^0.5.2+1
#  path_provider: 1.6.28
#  path: ^1.6.2
#  http: ^0.12.2
#  json_annotation:
#
#  #  multi_image_picker: ^4.7.14
#  #  flutter_absolute_path: ^1.0.6
#  jiffy: ^3.0.1
#  #  video_thumbnail: ^0.2.2
#  #  thumbnails: ^1.0.1
#  progress_indicators: ^0.1.5
#  #  gradient_widgets: ^0.5.2
#  #  flutter_appavailability: ^0.0.21
#  syncfusion_flutter_charts: ^18.4.47
#  #syncfusion_flutter_core: 18.4.49
#  #  date_picker_timeline: ^1.2.1
#  #  flutter_cupertino_data_picker: ^0.8.6
#  #  spider_chart:
#  #    git:
#  #      url: git://github.com/AnhDV580/flutter-spider-chart.git
#  retrofit:
#  analyzer:
#  intl_utils:
#  #  flushbar: ^1.10.4
#  hive: 1.4.4+1
#  hive_flutter:
#  shimmer:
#  pie_chart: 4.0.1
#  flutter_picker: 1.1.5
#  #Parse XML
#  xml: ^4.5.1
#  #WebView
#  # flutter_inappwebview: ^4.0.0+4
#  # Because Fix bug cannot switch keyboard in Android
#  # https://app.asana.com/0/1199670927722093/1199559492406925/f -> Change flutter_inappwebview fork from github
#  flutter_inappwebview:
#  #Laucher
#  url_launcher: ^5.7.10
#  #Calendar
#  table_calendar: ^2.3.0
#  #Reactive
#  rxdart: ^0.24.1
#  flutter_html: ^1.1.1
#  image: ^2.1.19
#  #Convert
#  flutter_image_compress: ^0.7.0
#  #flutter_appavailability: ^0.0.21
#  #Connectivity
#  connectivity: ^2.0.2
#  #flushbar
#  flushbar: ^1.10.4
#  wakelock: ^0.2.1+1
#  flutter_switch: 0.2.2
#  health:
#  #shared_preferences: 0.5.12+4
#  overlay_support:
#  firebase_core: ^0.7.0
#  firebase_dynamic_links: ^0.7.0+1
dev_dependencies:
  package_info: ^0.4.0+13
  retrofit_generator: ^1.3.7
  build_runner: ^1.1.10
  json_serializable: ^3.3.0

dependency_overrides:
  #Resolve 'build_runner' not working
#  analyzer: 0.39.17
#  build_resolvers: 1.3.10
#  flutter_inappwebview:
#    git:
#      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
#      ref: eaad17eb4fa8f3f3c575127a27c39b0a54abba8b
#  health:
#    git:
#      url: https://github.com/VietanhDoan/flutter-plugins.git
#      ref: 4332136296a3115b5b6b992c1456a6b81c288f02
#      path: packages/health
#  video_player:
#    path: lib_3rd/video_player-1.0.1
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
